-- ISTQB for ninjas v0.1
-- The MVP intentionally has exactly two application tables.

create table public.questions (
  id bigint generated by default as identity primary key,
  question_text text not null check (length(trim(question_text)) > 0),
  required_selections smallint not null check (required_selections >= 1),
  explanation text not null check (length(trim(explanation)) > 0),
  enabled boolean not null default true,
  date_added timestamptz not null default now(),
  date_edited timestamptz not null default now()
);

create table public.answers (
  id bigint generated by default as identity primary key,
  question_id bigint not null references public.questions(id) on delete cascade,
  answer_text text not null check (length(trim(answer_text)) > 0),
  correct boolean not null,
  date_added timestamptz not null default now(),
  date_edited timestamptz not null default now()
);

create index answers_question_id_idx on public.answers(question_id);
create index questions_enabled_idx on public.questions(enabled) where enabled = true;

create function public.touch_question_date_edited()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.date_edited = now();
  return new;
end;
$$;

create trigger questions_touch_date_edited
before update on public.questions
for each row execute function public.touch_question_date_edited();

create function public.touch_answer_date_edited()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.date_edited = now();
  return new;
end;
$$;

create trigger answers_touch_date_edited
before update on public.answers
for each row execute function public.touch_answer_date_edited();

create function public.validate_enabled_question()
returns trigger
language plpgsql
set search_path = ''
as $$
declare
  target_id bigint;
  selection_count smallint;
  is_enabled boolean;
  answer_count bigint;
  correct_count bigint;
begin
  if tg_table_name = 'questions' then
    target_id := case when tg_op = 'DELETE' then old.id else new.id end;
  else
    target_id := case when tg_op = 'DELETE' then old.question_id else new.question_id end;
  end if;

  select q.required_selections, q.enabled
    into selection_count, is_enabled
    from public.questions q
    where q.id = target_id;

  if is_enabled then
    select count(*), count(*) filter (where a.correct)
      into answer_count, correct_count
      from public.answers a
      where a.question_id = target_id;

    if answer_count < 2 then
      raise exception 'Enabled question % must have at least two answers', target_id;
    end if;

    if correct_count <> selection_count then
      raise exception 'Enabled question % requires % selections but has % correct answers',
        target_id, selection_count, correct_count;
    end if;
  end if;

  return null;
end;
$$;

create constraint trigger validate_question_row
after insert or update on public.questions
deferrable initially deferred
for each row execute function public.validate_enabled_question();

create constraint trigger validate_answer_rows
after insert or update or delete on public.answers
deferrable initially deferred
for each row execute function public.validate_enabled_question();

-- Browser clients receive no direct table access. Server routes use the
-- service-role key and expose only the fields appropriate for each phase.
alter table public.questions enable row level security;
alter table public.answers enable row level security;
